apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o03tu7lww-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o03tu7lww-nodejs 
  name: o03tu7lww-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: o03tu7lww-nodejs 
